FROM node:20-alpine AS builder
WORKDIR /app
ENV CI=true

COPY package.json package-lock.json* ./
RUN npm ci

COPY . .
RUN npm run build

FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=3000

COPY --from=builder /app ./
EXPOSE 3000

CMD ["npm", "run", "start"]
